export const DATA_SOURCE = 'DATA_SOURCE';
export const CATEGORIES_REPOSITORY = 'CATEGORIES_REPOSITORY';
export const CATEGORY_SNAPSHOT_REPOSITORY = 'CATEGORY_SNAPSHOT_REPOSITORY';
export const MONTHLY_INIT_LOG_REPOSITORY = 'MONTHLY_INIT_LOG_REPOSITORY';
export const TRANSACTION_REPOSITORY = 'TRANSACTION_REPOSITORY';
